CXX = g++
MAKEFILE := $(abspath $(lastword $(MAKEFILE_LIST)))
ROOT     := $(dir $(MAKEFILE))
TEMPLATE := $(ROOT)Snippets/template.cpp

CXXFLAGS = -I$(ROOT) -fsanitize=address,undefined -fno-omit-frame-pointer -g -Wall -Wshadow -std=c++17 \
           -Wno-unused-result -Wno-sign-compare -Wno-char-subscripts

%.cpp:
	@cp $(TEMPLATE) $@

%: %.cpp
	$(CXX) $(CXXFLAGS) $< -o $@
	./$@